# sample config for gconf app (do not put secrets here)

tg_session_path: gconf/data/sessions/gconf_support.session
drive:
  gconf_root_folder_id: "<drive_folder_id>"
  exports_folder_id: "<folder_id>"
  inputs_folder_id: "<folder_id>"
  spreadsheet_title_prefix: "gconf"





